### ISSUE TITLE
include .inc files with same syntax as .ini files

### ISSUE THREAD

**Issue by piflixe** [PeterMue/vscode-linuxcnc#4]
First of all, thank you for providing this syntax highlighting extension. Just makes working with the config files a lot easier!

In the progress of setting up a digital twin version of my real machines, I was looking for a nice way of managing the part of the ini file that is identical in both simulation and real machine. [Replies from the forum](https://forum.linuxcnc.org/49-basic-configuration/47371-best-practice-for-creating-a-digital-twin-simulation-version-of-a-real-machi#256619) pointed out that in the .ini files an #INCLUDE can be used. For some reason, it is recommended not to use .ini extension for the files to be included but .inc 

So my request is to include the .inc extension in this vscode extension apply the same syntax highlighting as with the .ini files. 

Thank you!

**Comment by PeterMue** [comment]
Thank you for your feedback!
I'll have a look at this maybe at the weekend.
Shouldn't be a big deal ;-)

**Comment by PeterMue** [comment]
Just release version 0.2.1 publicly to the marketplace.
